### ISSUE TITLE
image and qt* packages are failed to build with MSVC 2015 due to conda download wrong dependencies

### ISSUE THREAD

**Issue by e13000** [BTNC/distro-win#11]
Image package is failed to build on 2015 because jpeg.lib contains unresolved references to __iob_func, fprintf, and fscanf. After some investigation, I found that conda installs packages which may not match the current compiler version (in my case, jpeg [vc9] was installed instead of jpeg [vc14]). Due to the internal changes of MSVC2015's standard libraries, library files built by previous MSVC versions cannot be linked.  The following patch solves this issue.

[msvc2015_build.patch.txt](https://github.com/BTNC/distro-win/files/626509/msvc2015_build.patch.txt)

**Comment by BTNC** [comment]
Merged. However it sounds like a bug for conda if it is true, or there are some other issues undiscovered.
