### ISSUE TITLE
luaffifb can not be build in vs2015

### ISSUE THREAD

**Issue by lidongyv** [BTNC/distro-win#5]
many errors,can not be fixed

**Comment by BTNC** [comment]
Please refer to [this line](https://github.com/BTNC/distro-win/blob/master/install.bat#L23) on how to build luaffifb. If you still see compilation errors, post your error log. If you have luaffifb usage questions, please refer to [its official web site](https://github.com/facebook/luaffifb).

**Comment by lidongyv** [comment]
@BTNC sorry ,i forget to close this issue. I have succeed to install torch in windows,thanks a lot ,
