### ISSUE TITLE
Build Error: link error in wineditline

### ISSUE THREAD

**Issue by HaisongDing** [BTNC/distro-win#7]
wineditline has updated from 2.101 to 2.201 and the prebuild on [sourceforge](https://sourceforge.net/projects/mingweditline/) are build with MSVC2015. This will cause LINK error in building process (with MSVC2013)

**Comment by BTNC** [comment]
Please refer to [this line in install-deps.bat](https://github.com/BTNC/distro-win/blob/master/install-deps.bat#L319), wineditline is always compiled from source instead of using the prebuilt lib/dll.

Could you post your error output of running install.bat?

**Comment by HaisongDing** [comment]
I figure out what is wrong. I compile wineditline with MSVC2013 follow [this](http://mingweditline.sourceforge.net/?Downloads) step and replace edit_static.lib and dll files in wineditline.zip , and it all works out.
I notice the line you refered in install-deps.bat but it seems that it just unzip wineditline.zip and the compilation from source does not happen.

**Comment by HaisongDing** [comment]
[Line 319 in install-deps.bat](https://github.com/BTNC/distro-win/blob/master/install-deps.bat#L319) cause a cmake error: folder does not contain cmakelist file, so my guess is that [Line 318](https://github.com/BTNC/distro-win/blob/master/install-deps.bat#L318) does not enter wineditline-2.201 folder successfully.

**Comment by BTNC** [comment]
It turns out wget is now getting tar.bz2 file instead of the zip file from default link, and the downloaded file is not properly unzipped. This repo has been updated to download the zip file.
Thanks for the report!

**Comment by HaisongDing** [comment]
No problem. Also thanks for your amazing work that I can play torch on Windows.
