### ISSUE TITLE
Error: Unsatisfiable package specifications.

### ISSUE THREAD

**Issue by GarrickLin** [BTNC/distro-win#8]
```
+++++++ Installing openblas by conda, since there is no blas library specified
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
```
Hi, it occurs when I am running `install.bat`. Is that a version problem? My conda version is 3.10.0.

**Comment by BTNC** [comment]
I only tested with conda4. I suggest you upgrade your conda and retry (3.10.0 is more than one and a half years old). If you want to resolve the unsatisfiability, you could run the following command to see the unsatisfiability hint:
for x64: `conda install -n %TORCH_CONDA_ENV% -c ukoethe openblas --alt-hint`
for x86 `conda install -n %TORCH_CONDA_ENV% -c omnia   openblas --alt-hint`
replace `%TORCH_CONDA_ENV%` with the installed torch env name. If you do not know the name, you can find out by running `conda env list`

**Comment by GarrickLin** [comment]
yep! I solved this problem by running: 
```
conda update conda
```
